// Generated by https://quicktype.io

export interface RoomsChats {
    room:     string;
    messages: number;
}

export interface messageChat {
    room:     string;
    message: string;
    username : string;
    usernameSocket ?: string;
    valueNumber ?: number
}